services:
  db:
    image: postgres:16.4-alpine
    container_name: pg_${SERVICE_NAME}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: /data/postgres
    env_file:
      - .env
    volumes:
      - .docker/${SERVICE_ENV}/pg-data:/data/postgres
    ports:
      - "127.0.0.1:${DB_PORT}:5432"
    networks:
      - localnet
    restart: unless-stopped
    # Check DB health
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  migrate:
    image: migrate/migrate
    container_name: ${SERVICE_ENV}_migrate_${SERVICE_NAME}
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    entrypoint:
      [
        "sh",
        "-c",
        "migrate -path=/migrations -database=postgres://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${DB_DATABASE}?sslmode=disable up",
      ]
    volumes:
      - ./migrations:/migrations
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
